// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RecipientName string             `json:"recipient_name"`
	PhoneNumber   string             `json:"phone_number"`
	Province      string             `json:"province"`
	City          string             `json:"city"`
	District      string             `json:"district"`
	PostalCode    string             `json:"postal_code"`
	FullAddress   string             `json:"full_address"`
	Label         pgtype.Text        `json:"label"`
	Coordinates   pgtype.Text        `json:"coordinates"`
	IsPrimary     bool               `json:"is_primary"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Cart struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	IconImageUrl   pgtype.Text        `json:"icon_image_url"`
	BannerImageUrl pgtype.Text        `json:"banner_image_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type ProductVariant struct {
	ID               int64              `json:"id"`
	ProductID        int64              `json:"product_id"`
	VariantName      string             `json:"variant_name"`
	PriceExtra       pgtype.Numeric     `json:"price_extra"`
	Stock            int32              `json:"stock"`
	StockKeepingUnit string             `json:"stock_keeping_unit"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ProductsImage struct {
	ID        int64              `json:"id"`
	ProductID int64              `json:"product_id"`
	ImageUrl  string             `json:"image_url"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Password    string             `json:"password"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
