// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusProcessing OrderStatus = "processing"
	OrderStatusShipped    OrderStatus = "shipped"
	OrderStatusDelivered  OrderStatus = "delivered"
	OrderStatusCancelled  OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Address struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RecipientName string             `json:"recipient_name"`
	PhoneNumber   string             `json:"phone_number"`
	Province      string             `json:"province"`
	City          string             `json:"city"`
	District      string             `json:"district"`
	PostalCode    string             `json:"postal_code"`
	FullAddress   string             `json:"full_address"`
	Label         pgtype.Text        `json:"label"`
	Coordinates   pgtype.Text        `json:"coordinates"`
	IsPrimary     bool               `json:"is_primary"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Cart struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CartItem struct {
	ID               pgtype.UUID        `json:"id"`
	CartID           pgtype.UUID        `json:"cart_id"`
	ProductID        int64              `json:"product_id"`
	ProductVariantID pgtype.Int8        `json:"product_variant_id"`
	Quantity         int32              `json:"quantity"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	IconImageUrl   pgtype.Text        `json:"icon_image_url"`
	BannerImageUrl pgtype.Text        `json:"banner_image_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InvoiceNumber   string             `json:"invoice_number"`
	Status          OrderStatus        `json:"status"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	ShippingCost    pgtype.Numeric     `json:"shipping_cost"`
	GrandTotal      pgtype.Numeric     `json:"grand_total"`
	ShippingAddress string             `json:"shipping_address"`
	TrackingNumber  pgtype.Text        `json:"tracking_number"`
	CourierName     pgtype.Text        `json:"courier_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID               pgtype.UUID        `json:"id"`
	OrderID          pgtype.UUID        `json:"order_id"`
	ProductID        int64              `json:"product_id"`
	ProductVariantID pgtype.Int8        `json:"product_variant_id"`
	ProductName      string             `json:"product_name"`
	Quantity         int32              `json:"quantity"`
	PriceAtPurchase  pgtype.Numeric     `json:"price_at_purchase"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PasswordReset struct {
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type ProductImage struct {
	ID        int64              `json:"id"`
	ProductID int64              `json:"product_id"`
	ImageUrl  string             `json:"image_url"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProductVariant struct {
	ID               int64              `json:"id"`
	ProductID        int64              `json:"product_id"`
	VariantName      string             `json:"variant_name"`
	PriceExtra       pgtype.Numeric     `json:"price_extra"`
	Stock            int32              `json:"stock"`
	StockKeepingUnit string             `json:"stock_keeping_unit"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Password    string             `json:"password"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
