// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	IconImageUrl   pgtype.Text        `json:"icon_image_url"`
	BannerImageUrl pgtype.Text        `json:"banner_image_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Password    string             `json:"password"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
