// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addItemToCart = `-- name: AddItemToCart :one
INSERT INTO cart_items (cart_id, product_id, product_variant_id, quantity)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, product_id, (COALESCE(product_variant_id, 0)))
DO UPDATE SET 
    quantity = cart_items.quantity + EXCLUDED.quantity,
    updated_at = NOW()
RETURNING id, cart_id, product_id, product_variant_id, quantity, created_at, updated_at
`

type AddItemToCartParams struct {
	CartID           pgtype.UUID `json:"cart_id"`
	ProductID        int64       `json:"product_id"`
	ProductVariantID pgtype.Int8 `json:"product_variant_id"`
	Quantity         int32       `json:"quantity"`
}

func (q *Queries) AddItemToCart(ctx context.Context, arg AddItemToCartParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addItemToCart,
		arg.CartID,
		arg.ProductID,
		arg.ProductVariantID,
		arg.Quantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCartItems = `-- name: ClearCartItems :exec
DELETE FROM cart_items
WHERE cart_id IN (SELECT id FROM carts WHERE user_id = $1)
`

func (q *Queries) ClearCartItems(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCartItems, userID)
	return err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products 
WHERE deleted_at IS NULL
  AND (name ILIKE '%' || $1::text || '%' OR $1::text = '')
`

func (q *Queries) CountProducts(ctx context.Context, searchQuery string) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, searchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id, invoice_number, status, total_amount,
    shipping_cost, grand_total, shipping_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, invoice_number, status, total_amount, shipping_cost, grand_total, shipping_address, tracking_number, courier_name, created_at, updated_at
`

type CreateOrderParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	InvoiceNumber   string         `json:"invoice_number"`
	Status          OrderStatus    `json:"status"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	ShippingCost    pgtype.Numeric `json:"shipping_cost"`
	GrandTotal      pgtype.Numeric `json:"grand_total"`
	ShippingAddress string         `json:"shipping_address"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.InvoiceNumber,
		arg.Status,
		arg.TotalAmount,
		arg.ShippingCost,
		arg.GrandTotal,
		arg.ShippingAddress,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvoiceNumber,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingCost,
		&i.GrandTotal,
		&i.ShippingAddress,
		&i.TrackingNumber,
		&i.CourierName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, product_variant_id, product_name, quantity, price_at_purchase
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, order_id, product_id, product_variant_id, product_name, quantity, price_at_purchase, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID          pgtype.UUID    `json:"order_id"`
	ProductID        int64          `json:"product_id"`
	ProductVariantID pgtype.Int8    `json:"product_variant_id"`
	ProductName      string         `json:"product_name"`
	Quantity         int32          `json:"quantity"`
	PriceAtPurchase  pgtype.Numeric `json:"price_at_purchase"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductVariantID,
		arg.ProductName,
		arg.Quantity,
		arg.PriceAtPurchase,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.ProductName,
		&i.Quantity,
		&i.PriceAtPurchase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, name, slug, description, base_price, 
    discount_price, weight, specifications
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, category_id, name, slug, description, base_price, discount_price, weight, specifications, rating_average, rating_count, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID     pgtype.Int8    `json:"category_id"`
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Description    pgtype.Text    `json:"description"`
	BasePrice      pgtype.Numeric `json:"base_price"`
	DiscountPrice  pgtype.Numeric `json:"discount_price"`
	Weight         int32          `json:"weight"`
	Specifications []byte         `json:"specifications"`
}

type CreateProductRow struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.BasePrice,
		arg.DiscountPrice,
		arg.Weight,
		arg.Specifications,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.DiscountPrice,
		&i.Weight,
		&i.Specifications,
		&i.RatingAverage,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, name, email, password, phone_number)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, name, email, phone_number, created_at
`

type CreateUserParams struct {
	Username    string      `json:"username"`
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasswordReset = `-- name: DeletePasswordReset :exec
DELETE FROM password_resets
WHERE email = $1
`

func (q *Queries) DeletePasswordReset(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deletePasswordReset, email)
	return err
}

const findCategoryByID = `-- name: FindCategoryByID :one
SELECT id, name, slug, description, icon_image_url, banner_image_url, is_active, created_at, updated_at
FROM categories
WHERE id = $1 AND is_active = true
`

func (q *Queries) FindCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IconImageUrl,
		&i.BannerImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPasswordResetByToken = `-- name: FindPasswordResetByToken :one
SELECT email, token, expires_at
FROM password_resets
WHERE token = $1
`

type FindPasswordResetByTokenRow struct {
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) FindPasswordResetByToken(ctx context.Context, token string) (FindPasswordResetByTokenRow, error) {
	row := q.db.QueryRow(ctx, findPasswordResetByToken, token)
	var i FindPasswordResetByTokenRow
	err := row.Scan(&i.Email, &i.Token, &i.ExpiresAt)
	return i, err
}

const findProductByID = `-- name: FindProductByID :one
SELECT 
    id, category_id, name, slug, description, base_price, 
    discount_price, weight, specifications, rating_average, 
    rating_count, created_at, updated_at
FROM products 
WHERE id = $1 AND deleted_at IS NULL
`

type FindProductByIDRow struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Untuk detail satu produk, baru kita tarik seluruh data beratnya.
func (q *Queries) FindProductByID(ctx context.Context, id int64) (FindProductByIDRow, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i FindProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.DiscountPrice,
		&i.Weight,
		&i.Specifications,
		&i.RatingAverage,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductDetailBySlug = `-- name: FindProductDetailBySlug :one
SELECT 
    p.id, p.category_id, p.name, p.slug, p.description, p.base_price, 
    p.discount_price, p.weight, p.specifications, p.rating_average, 
    p.rating_count, p.created_at,
    COALESCE(
        (SELECT jsonb_agg(
            jsonb_build_object('id', pi.id, 'image_url', pi.image_url, 'sort_order', pi.sort_order)
        ) FROM (
            SELECT id, image_url, sort_order 
            FROM product_images 
            WHERE product_id = p.id 
            ORDER BY sort_order ASC
        ) pi), 
    '[]'::jsonb) AS images,
    COALESCE(
        (SELECT jsonb_agg(
            jsonb_build_object('id', pv.id, 'variant_name', pv.variant_name, 'price_extra', pv.price_extra, 'stock', pv.stock)
        ) FROM product_variants pv 
        WHERE pv.product_id = p.id AND pv.deleted_at IS NULL), 
    '[]'::jsonb) AS variants
FROM products p
WHERE p.slug = $1 AND p.deleted_at IS NULL
`

type FindProductDetailBySlugRow struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Images         interface{}        `json:"images"`
	Variants       interface{}        `json:"variants"`
}

func (q *Queries) FindProductDetailBySlug(ctx context.Context, slug string) (FindProductDetailBySlugRow, error) {
	row := q.db.QueryRow(ctx, findProductDetailBySlug, slug)
	var i FindProductDetailBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.DiscountPrice,
		&i.Weight,
		&i.Specifications,
		&i.RatingAverage,
		&i.RatingCount,
		&i.CreatedAt,
		&i.Images,
		&i.Variants,
	)
	return i, err
}

const findUserByEmailForLogin = `-- name: FindUserByEmailForLogin :one
SELECT id, name, email, password
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type FindUserByEmailForLoginRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
}

func (q *Queries) FindUserByEmailForLogin(ctx context.Context, email string) (FindUserByEmailForLoginRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmailForLogin, email)
	var i FindUserByEmailForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT 
    id, name, email, phone_number, created_at
FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

type FindUserByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Untuk detail user (misal untuk update profile), kita tidak menarik 'password' juga.
func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT 
    ci.id, ci.cart_id, ci.product_id, ci.product_variant_id, ci.quantity, ci.created_at, ci.updated_at,
    p.name as product_name, p.slug as product_slug, p.base_price as product_price,
    COALESCE(img.image_url, '')::TEXT as product_image,
    pv.variant_name, pv.price_extra as variant_price_extra
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
LEFT JOIN LATERAL (
    SELECT image_url 
    FROM product_images 
    WHERE product_id = p.id 
    ORDER BY sort_order ASC 
    LIMIT 1
) img ON true
LEFT JOIN product_variants pv ON pv.id = ci.product_variant_id
WHERE ci.cart_id = $1
ORDER BY ci.created_at ASC
`

type ListCartItemsRow struct {
	ID                pgtype.UUID        `json:"id"`
	CartID            pgtype.UUID        `json:"cart_id"`
	ProductID         int64              `json:"product_id"`
	ProductVariantID  pgtype.Int8        `json:"product_variant_id"`
	Quantity          int32              `json:"quantity"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProductName       string             `json:"product_name"`
	ProductSlug       string             `json:"product_slug"`
	ProductPrice      pgtype.Numeric     `json:"product_price"`
	ProductImage      string             `json:"product_image"`
	VariantName       pgtype.Text        `json:"variant_name"`
	VariantPriceExtra pgtype.Numeric     `json:"variant_price_extra"`
}

func (q *Queries) ListCartItems(ctx context.Context, cartID pgtype.UUID) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsRow
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ProductSlug,
			&i.ProductPrice,
			&i.ProductImage,
			&i.VariantName,
			&i.VariantPriceExtra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarts = `-- name: ListCarts :many
SELECT id, user_id, created_at, updated_at
FROM carts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCarts(ctx context.Context, userID pgtype.UUID) ([]Cart, error) {
	rows, err := q.db.Query(ctx, listCarts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, icon_image_url, banner_image_url, is_active, created_at, updated_at
FROM categories
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IconImageUrl,
			&i.BannerImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, product_variant_id, product_name, quantity, price_at_purchase, created_at, updated_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.ProductName,
			&i.Quantity,
			&i.PriceAtPurchase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, invoice_number, status, total_amount, shipping_cost, grand_total, shipping_address, tracking_number, courier_name, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context, userID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InvoiceNumber,
			&i.Status,
			&i.TotalAmount,
			&i.ShippingCost,
			&i.GrandTotal,
			&i.ShippingAddress,
			&i.TrackingNumber,
			&i.CourierName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, image_url, sort_order
FROM product_images
WHERE product_id = $1
ORDER BY sort_order ASC
`

type ListProductImagesRow struct {
	ID        int64  `json:"id"`
	ImageUrl  string `json:"image_url"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) ListProductImages(ctx context.Context, productID int64) ([]ListProductImagesRow, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductImagesRow
	for rows.Next() {
		var i ListProductImagesRow
		if err := rows.Scan(&i.ID, &i.ImageUrl, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT id, variant_name, price_extra, stock, stock_keeping_unit
FROM product_variants
WHERE product_id = $1 AND deleted_at IS NULL
`

type ListProductVariantsRow struct {
	ID               int64          `json:"id"`
	VariantName      string         `json:"variant_name"`
	PriceExtra       pgtype.Numeric `json:"price_extra"`
	Stock            int32          `json:"stock"`
	StockKeepingUnit string         `json:"stock_keeping_unit"`
}

func (q *Queries) ListProductVariants(ctx context.Context, productID int64) ([]ListProductVariantsRow, error) {
	rows, err := q.db.Query(ctx, listProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductVariantsRow
	for rows.Next() {
		var i ListProductVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantName,
			&i.PriceExtra,
			&i.Stock,
			&i.StockKeepingUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT 
    p.id, p.category_id, p.name, p.slug, p.base_price, p.discount_price, 
    p.rating_average, p.rating_count, p.created_at,
    COALESCE(img.image_url, '')::TEXT as main_image
FROM products p
LEFT JOIN LATERAL (
    SELECT image_url FROM product_images WHERE product_id = p.id ORDER BY sort_order ASC LIMIT 1
) img ON true
WHERE p.deleted_at IS NULL 
  AND (p.created_at < $1 OR $1 IS NULL) -- $1 adalah waktu dari item terakhir di halaman sebelumnya
ORDER BY p.created_at DESC
LIMIT $2
`

type ListProductsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type ListProductsRow struct {
	ID            int64              `json:"id"`
	CategoryID    pgtype.Int8        `json:"category_id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	BasePrice     pgtype.Numeric     `json:"base_price"`
	DiscountPrice pgtype.Numeric     `json:"discount_price"`
	RatingAverage pgtype.Numeric     `json:"rating_average"`
	RatingCount   int32              `json:"rating_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	MainImage     string             `json:"main_image"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.BasePrice,
			&i.DiscountPrice,
			&i.RatingAverage,
			&i.RatingCount,
			&i.CreatedAt,
			&i.MainImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsOffset = `-- name: ListProductsOffset :many
SELECT 
    p.id, p.category_id, p.name, p.slug, p.base_price, p.discount_price, 
    p.rating_average, p.rating_count, p.created_at,
    COALESCE(img.image_url, '')::TEXT as main_image
FROM products p
LEFT JOIN LATERAL (
    SELECT image_url FROM product_images WHERE product_id = p.id ORDER BY sort_order ASC LIMIT 1
) img ON true
WHERE p.deleted_at IS NULL 
  AND (p.name ILIKE '%' || $3::text || '%' OR $3::text = '')
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsOffsetParams struct {
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
	SearchQuery string `json:"search_query"`
}

type ListProductsOffsetRow struct {
	ID            int64              `json:"id"`
	CategoryID    pgtype.Int8        `json:"category_id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	BasePrice     pgtype.Numeric     `json:"base_price"`
	DiscountPrice pgtype.Numeric     `json:"discount_price"`
	RatingAverage pgtype.Numeric     `json:"rating_average"`
	RatingCount   int32              `json:"rating_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	MainImage     string             `json:"main_image"`
}

func (q *Queries) ListProductsOffset(ctx context.Context, arg ListProductsOffsetParams) ([]ListProductsOffsetRow, error) {
	rows, err := q.db.Query(ctx, listProductsOffset, arg.Limit, arg.Offset, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsOffsetRow
	for rows.Next() {
		var i ListProductsOffsetRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.BasePrice,
			&i.DiscountPrice,
			&i.RatingAverage,
			&i.RatingCount,
			&i.CreatedAt,
			&i.MainImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT 
    id, name, email, phone_number, created_at
FROM users
WHERE deleted_at IS NULL
`

type ListUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Mengecualikan 'password' untuk keamanan.
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeItemFromCart = `-- name: RemoveItemFromCart :exec
DELETE FROM cart_items
WHERE id = $1
`

func (q *Queries) RemoveItemFromCart(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeItemFromCart, id)
	return err
}

const updateItemQuantity = `-- name: UpdateItemQuantity :one
UPDATE cart_items
SET quantity = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, cart_id, product_id, product_variant_id, quantity, created_at, updated_at
`

type UpdateItemQuantityParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2
WHERE email = $1
`

type UpdateUserPasswordParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Email, arg.Password)
	return err
}

const upsertPasswordReset = `-- name: UpsertPasswordReset :exec
INSERT INTO password_resets (email, token, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE SET
    token = EXCLUDED.token,
    expires_at = EXCLUDED.expires_at,
    created_at = CURRENT_TIMESTAMP
`

type UpsertPasswordResetParams struct {
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertPasswordReset(ctx context.Context, arg UpsertPasswordResetParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordReset, arg.Email, arg.Token, arg.ExpiresAt)
	return err
}
