// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindCategoryByID(ctx context.Context, id int64) (Category, error)
	// Untuk detail satu produk, baru kita tarik seluruh data beratnya.
	FindProductByID(ctx context.Context, id int64) (FindProductByIDRow, error)
	FindProductBySlug(ctx context.Context, slug string) (FindProductBySlugRow, error)
	FindUserByEmailForLogin(ctx context.Context, email string) (FindUserByEmailForLoginRow, error)
	// Untuk detail user (misal untuk update profile), kita tidak menarik 'password' juga.
	FindUserByID(ctx context.Context, id pgtype.UUID) (FindUserByIDRow, error)
	ListCarts(ctx context.Context, userID pgtype.UUID) ([]Cart, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListProductImages(ctx context.Context, productID int64) ([]ListProductImagesRow, error)
	ListProductVariants(ctx context.Context, productID int64) ([]ListProductVariantsRow, error)
	// Untuk daftar produk, kita tidak menarik 'description' dan 'specifications' agar payload ringan.
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	// Mengecualikan 'password' untuk keamanan.
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
}

var _ Querier = (*Queries)(nil)
