// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, name, slug, description, base_price, 
    discount_price, weight, specifications
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, category_id, name, slug, description, base_price, discount_price, weight, specifications, rating_average, rating_count, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID     pgtype.Int8    `json:"category_id"`
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Description    pgtype.Text    `json:"description"`
	BasePrice      pgtype.Numeric `json:"base_price"`
	DiscountPrice  pgtype.Numeric `json:"discount_price"`
	Weight         int32          `json:"weight"`
	Specifications []byte         `json:"specifications"`
}

type CreateProductRow struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.BasePrice,
		arg.DiscountPrice,
		arg.Weight,
		arg.Specifications,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.DiscountPrice,
		&i.Weight,
		&i.Specifications,
		&i.RatingAverage,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, name, email, password, phone_number)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, name, email, phone_number, created_at
`

type CreateUserParams struct {
	Username    string      `json:"username"`
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const findCategoryByID = `-- name: FindCategoryByID :one
SELECT id, name, slug, description, icon_image_url, banner_image_url, is_active, created_at, updated_at
FROM categories
WHERE id = $1 AND is_active = true
`

func (q *Queries) FindCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IconImageUrl,
		&i.BannerImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductByID = `-- name: FindProductByID :one
SELECT 
    id, category_id, name, slug, description, base_price, 
    discount_price, weight, specifications, rating_average, 
    rating_count, created_at, updated_at
FROM products 
WHERE id = $1 AND deleted_at IS NULL
`

type FindProductByIDRow struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Untuk detail satu produk, baru kita tarik seluruh data beratnya.
func (q *Queries) FindProductByID(ctx context.Context, id int64) (FindProductByIDRow, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i FindProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.DiscountPrice,
		&i.Weight,
		&i.Specifications,
		&i.RatingAverage,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductBySlug = `-- name: FindProductBySlug :one
SELECT 
    id, category_id, name, slug, description, base_price, 
    discount_price, weight, specifications, rating_average, 
    rating_count, created_at, updated_at
FROM products 
WHERE slug = $1 AND deleted_at IS NULL
`

type FindProductBySlugRow struct {
	ID             int64              `json:"id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BasePrice      pgtype.Numeric     `json:"base_price"`
	DiscountPrice  pgtype.Numeric     `json:"discount_price"`
	Weight         int32              `json:"weight"`
	Specifications []byte             `json:"specifications"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindProductBySlug(ctx context.Context, slug string) (FindProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, findProductBySlug, slug)
	var i FindProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.DiscountPrice,
		&i.Weight,
		&i.Specifications,
		&i.RatingAverage,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmailForLogin = `-- name: FindUserByEmailForLogin :one
SELECT id, name, email, password
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type FindUserByEmailForLoginRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
}

func (q *Queries) FindUserByEmailForLogin(ctx context.Context, email string) (FindUserByEmailForLoginRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmailForLogin, email)
	var i FindUserByEmailForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT 
    id, name, email, phone_number, created_at
FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

type FindUserByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Untuk detail user (misal untuk update profile), kita tidak menarik 'password' juga.
func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listCarts = `-- name: ListCarts :many
SELECT id, user_id, created_at, updated_at
FROM carts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCarts(ctx context.Context, userID pgtype.UUID) ([]Cart, error) {
	rows, err := q.db.Query(ctx, listCarts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, icon_image_url, banner_image_url, is_active, created_at, updated_at
FROM categories
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IconImageUrl,
			&i.BannerImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, image_url, sort_order
FROM product_images
WHERE product_id = $1
ORDER BY sort_order ASC
`

type ListProductImagesRow struct {
	ID        int64  `json:"id"`
	ImageUrl  string `json:"image_url"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) ListProductImages(ctx context.Context, productID int64) ([]ListProductImagesRow, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductImagesRow
	for rows.Next() {
		var i ListProductImagesRow
		if err := rows.Scan(&i.ID, &i.ImageUrl, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT id, variant_name, price_extra, stock, stock_keeping_unit
FROM product_variants
WHERE product_id = $1 AND deleted_at IS NULL
`

type ListProductVariantsRow struct {
	ID               int64          `json:"id"`
	VariantName      string         `json:"variant_name"`
	PriceExtra       pgtype.Numeric `json:"price_extra"`
	Stock            int32          `json:"stock"`
	StockKeepingUnit string         `json:"stock_keeping_unit"`
}

func (q *Queries) ListProductVariants(ctx context.Context, productID int64) ([]ListProductVariantsRow, error) {
	rows, err := q.db.Query(ctx, listProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductVariantsRow
	for rows.Next() {
		var i ListProductVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantName,
			&i.PriceExtra,
			&i.Stock,
			&i.StockKeepingUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT 
    id, category_id, name, slug, base_price, discount_price, 
    rating_average, rating_count, created_at
FROM products
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID            int64              `json:"id"`
	CategoryID    pgtype.Int8        `json:"category_id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	BasePrice     pgtype.Numeric     `json:"base_price"`
	DiscountPrice pgtype.Numeric     `json:"discount_price"`
	RatingAverage pgtype.Numeric     `json:"rating_average"`
	RatingCount   int32              `json:"rating_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Untuk daftar produk, kita tidak menarik 'description' dan 'specifications' agar payload ringan.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.BasePrice,
			&i.DiscountPrice,
			&i.RatingAverage,
			&i.RatingCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT 
    id, name, email, phone_number, created_at
FROM users
WHERE deleted_at IS NULL
`

type ListUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Mengecualikan 'password' untuk keamanan.
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
