version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mantis_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mantis
    ports:
      - "5432:5432"
    volumes:
      - mantis_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mantis_pg_data:
